import { useCallback, useEffect, useRef, useState } from 'react'
import { CalendarDays, CircleCheck, Clock3, FlaskConical, MapPin, Package, Pill, RefreshCw, Truck, TriangleAlert } from 'lucide-react'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Separator } from '@/components/ui/separator'
import { Skeleton } from '@/components/ui/skeleton'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import type { Order, TrackingResult, TrackingState } from './types'

const aud = (value: string | null | undefined) => value == null ? '—' : `A$${value.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`
const formatTrackingDate = (value: string | null) => {
  if (!value) return 'Not returned'
  const local = !/(?:Z|[+-]\d{2}:?\d{2})$/.test(value)
  const date = new Date(local ? `${value}Z` : value)
  return Number.isNaN(date.getTime()) ? 'Not returned' : new Intl.DateTimeFormat('en-AU', { dateStyle: 'medium', timeStyle: 'short', timeZone: local ? 'UTC' : 'Australia/Sydney' }).format(date) + (local ? ' (carrier local time)' : ' (Sydney)')
}
const formatOrderDate = (value: string) => {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return 'Not returned'
  const date = new Date(`${value}T00:00:00Z`)
  return Number.isNaN(date.getTime()) ? 'Not returned' : new Intl.DateTimeFormat('en-AU', { dateStyle: 'medium', timeZone: 'UTC' }).format(date)
}
async function api<T>(url: string): Promise<T> {
  const response = await fetch(url)
  if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(body?.detail || `Request failed (HTTP ${response.status})`) }
  return response.json() as Promise<T>
}

function TrackingCard({ result }: { result: TrackingResult }) {
  const available = result.availability === 'available'
  return <Card className="shadow-none" data-testid="tracking-card"><CardHeader className="gap-3">
    <div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><Truck className="size-4 text-muted-foreground" /><CardTitle className="text-sm">{result.carrier === 'tnt' ? 'TNT' : 'StarTrack / Australia Post'}</CardTitle></div><Badge variant={available ? 'secondary' : 'outline'}>{available ? 'Response received' : 'Unavailable'}</Badge></div>
    <CardDescription className="font-mono text-xs">{result.label} · {result.tracking_no}</CardDescription></CardHeader><CardContent className="space-y-4">
    {available ? <><div className="rounded-lg bg-muted/60 p-3"><p className="mb-1 flex items-center gap-2 text-sm font-medium"><CircleCheck className="size-4" />{result.status ?? 'Status not returned'}</p><p className="flex items-center gap-1.5 text-xs text-muted-foreground"><Clock3 className="size-3.5" />Last update: {formatTrackingDate(result.last_updated)}</p></div>
      {result.events.length > 0 && <details className="text-xs"><summary className="cursor-pointer rounded-sm py-1 font-medium focus-visible:outline-2 focus-visible:outline-ring">View tracking events ({result.events.length})</summary><ol className="mt-3 space-y-3 border-l pl-4">{result.events.map((event, index) => <li key={`${event.article_id}-${event.date}-${index}`}><p className="font-medium">{event.description || 'Description not returned'}</p><p className="text-muted-foreground">{formatTrackingDate(event.date)}{event.location ? ` · ${event.location}` : ''}</p></li>)}</ol></details>}
      <p className="flex items-center gap-1.5 text-[11px] text-muted-foreground">{result.source === 'tnt_domestic_public' ? <><Truck className="size-3.5" />TNT domestic tracking · official website response</> : <><FlaskConical className="size-3.5" />Test environment result · simulated parcel events</>}</p></> : <Alert className="border-dashed"><TriangleAlert className="size-4" /><AlertTitle>Tracking unavailable</AlertTitle><AlertDescription>{result.reason || 'No tracking information is available.'}</AlertDescription></Alert>}
  </CardContent></Card>
}

function ShippingBreakdown({ order }: { order: Order }) {
  const estimate = order.shipping_estimate
  return <details className="rounded-lg border bg-muted/30 p-3 text-xs" data-testid="shipping-breakdown"><summary className="cursor-pointer font-medium">Shipping estimate · {estimate.availability === 'estimated' ? 'All shipments estimated' : estimate.availability === 'partial' ? 'Partial estimate' : 'Unavailable'}</summary><div className="mt-3 space-y-3">{estimate.shipments.map(shipment => <div key={shipment.id} className="space-y-1 border-t pt-2"><p className="flex justify-between gap-3 font-medium"><span>{shipment.label} · {shipment.carrier === 'tnt' ? 'TNT' : 'StarTrack / Australia Post'}</span><span>{aud(shipment.fee)}</span></p>{shipment.availability === 'estimated' ? <><p className="text-muted-foreground">Packed weight: {shipment.actual_weight_kg} kg · Volumetric: {shipment.volumetric_weight_kg} kg</p><p className="text-muted-foreground">Chargeable: {shipment.chargeable_weight_kg} kg (rounded up to 0.5 kg)</p></> : <p className="text-muted-foreground">{shipment.reason}</p>}</div>)}<p className="text-muted-foreground">A$8 base + A$2/kg per shipment; postcode zone factor ×1 or ×1.25. Includes GST. See README for packaging assumptions.</p></div></details>
}

function Details({ order, state, refresh }: { order: Order; state?: TrackingState; refresh: () => void }) {
  return <div className="space-y-6"><Card className="shadow-none"><CardHeader className="gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="space-y-2"><p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Purchase order</p><CardTitle className="break-all text-xl tracking-tight sm:text-2xl">{order.order_no}</CardTitle><CardDescription className="flex items-center gap-2"><CalendarDays className="size-3.5" />{formatOrderDate(order.order_date)} · {order.company}</CardDescription></div><Badge variant="secondary" className="w-fit gap-1.5 px-3 py-1.5">{order.status === 'Completed' ? <CircleCheck className="size-3.5" /> : <Truck className="size-3.5" />}Order: {order.status}</Badge></CardHeader></Card>
    {order.issues.length > 0 && <Alert variant="destructive"><TriangleAlert /><AlertTitle>Order amounts cannot be calculated</AlertTitle><AlertDescription>{order.issues.join(' · ')}</AlertDescription></Alert>}
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="min-w-0 space-y-6"><Card className="overflow-hidden shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Package className="size-4" />Order items <Badge variant="outline">{order.items.length} lines</Badge></CardTitle><CardDescription>Retail prices include GST. Line subtotals exclude GST.</CardDescription></CardHeader><CardContent className="overflow-x-auto px-0"><Table className="min-w-[720px]"><TableHeader><TableRow className="bg-muted/40"><TableHead className="pl-6">Product</TableHead><TableHead>Qty</TableHead><TableHead className="text-right">RRP<br /><span className="text-[10px] font-normal">incl. GST</span></TableHead><TableHead className="text-right">Unit price<br /><span className="text-[10px] font-normal">ex GST</span></TableHead><TableHead className="pr-6 text-right">Line subtotal<br /><span className="text-[10px] font-normal">ex GST</span></TableHead></TableRow></TableHeader><TableBody>{order.items.map((line, index) => <TableRow key={`${line.sku}-${index}`}><TableCell className="py-4 pl-6"><div className="flex items-center gap-3"><div role="img" aria-label="Product image placeholder" className="flex size-14 shrink-0 flex-col items-center justify-center gap-1 rounded-lg border bg-muted/40 text-muted-foreground"><Pill className="size-5" /><span className="text-[8px]">Placeholder</span></div><div className="max-w-[245px] whitespace-normal"><p className="text-sm font-medium leading-5">{line.name}</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">{line.sku}</p><p className="mt-1 text-[10px] text-muted-foreground">{order.shipments.find(s => s.id === line.shipment_id)?.label ?? 'Unknown shipment'}</p>{line.issues.map((issue, i) => <p key={i} className="mt-1 text-xs text-destructive">{issue}</p>)}</div></div></TableCell><TableCell className="tabular-nums">{String(line.quantity ?? '—')}</TableCell><TableCell className="text-right tabular-nums">{aud(line.rrp)}</TableCell><TableCell className="text-right tabular-nums">{aud(line.ex_gst_unit_price)}</TableCell><TableCell className="pr-6 text-right font-medium tabular-nums">{aud(line.line_subtotal_ex_gst)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
      <div className="grid gap-6 md:grid-cols-2"><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><MapPin className="size-4" />Shipping information</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="font-medium">{order.customer}</p><p className="mt-1 text-muted-foreground">{order.company}</p></div><p className="leading-6">{order.shipping.address}<br />Australia</p><Separator /><div className="space-y-1.5 text-muted-foreground"><p>{order.phone}</p><p className="break-all">{order.email}</p></div><p className="text-xs text-muted-foreground">Origin: Ryde NSW 2111 · Destination: {order.shipping.postcode}</p></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle className="text-base">Order summary</CardTitle><CardDescription>AUD · GST 10% · line-level rounding</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal (ex GST)</span><span>{aud(order.summary?.subtotal_ex_gst)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">GST (10%)</span><span>{aud(order.summary?.gst)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Shipment Fee (estimate)</span><span>{aud(order.summary?.shipment_fee)}</span></div><Separator /><div className="flex justify-between pt-1"><span className="font-medium">Total</span><span className="text-xl font-semibold">{order.summary ? aud(order.summary.total) : 'Cannot calculate'}</span></div><ShippingBreakdown order={order} /><p className="pt-2 text-xs text-muted-foreground">Line-level tax rounding differences can accumulate. Shipping is a GST-inclusive local estimate, not a carrier quote.</p></CardContent></Card></div>
    </div><aside className="space-y-4" aria-label="Order tracking" aria-busy={state?.loading ?? true}><div className="flex items-center justify-between gap-2"><h2 className="text-base font-semibold">Logistics tracking</h2><Button variant="outline" size="sm" onClick={refresh} disabled={!state || state.loading}><RefreshCw className={state?.loading ? 'animate-spin' : ''} />{state?.loading ? 'Checking…' : 'Refresh tracking'}</Button></div><p className="text-xs leading-5 text-muted-foreground">Tracking is separate from order status. Australia Post uses the testbed; TNT uses its official domestic tracking website.</p>{!state || state.loading ? <div role="status" className="space-y-4">{order.shipments.map(s => <Card key={s.id} className="shadow-none"><CardContent className="space-y-3 pt-6"><Skeleton className="h-4 w-2/3" /><Skeleton className="h-3 w-1/2" /><Skeleton className="h-16 w-full" /></CardContent></Card>)}</div> : state.error ? <Alert variant="destructive"><TriangleAlert /><AlertTitle>Tracking could not be loaded</AlertTitle><AlertDescription>{state.error}</AlertDescription></Alert> : state.results.map(result => <TrackingCard key={result.id} result={result} />)}<div className="rounded-lg border border-dashed p-3 text-xs leading-5 text-muted-foreground"><p className="mb-1 flex items-center gap-1.5 font-medium text-foreground"><FlaskConical className="size-3.5" />Courier sources</p>Australia Post testbed events may be simulated. TNT history comes from the public domestic service; timestamps preserve carrier local time.</div></aside></div>
  </div>
}

export default function App() {
  const [orders, setOrders] = useState<Order[]>([]); const [active, setActive] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [tracking, setTracking] = useState<Record<string, TrackingState>>({}); const inFlight = useRef(new Set<string>())
  useEffect(() => { api<{ orders: Order[] }>('/api/orders').then(data => { setOrders(data.orders); setActive(data.orders[0]?.order_no || ''); setLoading(false) }).catch(cause => { setError(cause instanceof Error ? cause.message : 'Order service is unavailable'); setLoading(false) }) }, [])
  const getTracking = useCallback(async (orderNo: string) => { if (inFlight.current.has(orderNo)) return; inFlight.current.add(orderNo); setTracking(old => ({ ...old, [orderNo]: { loading: true, results: [], error: null } })); try { const data = await api<{ tracking: TrackingResult[]; summary: Order['summary']; shipping_estimate: Order['shipping_estimate'] }>(`/api/orders/${encodeURIComponent(orderNo)}/tracking`); setOrders(old => old.map(order => order.order_no === orderNo ? { ...order, summary: data.summary, shipping_estimate: data.shipping_estimate } : order)); setTracking(old => ({ ...old, [orderNo]: { loading: false, results: data.tracking, error: null } })) } catch (cause) { setTracking(old => ({ ...old, [orderNo]: { loading: false, results: [], error: cause instanceof Error ? cause.message : 'Tracking service is unavailable' } })) } finally { inFlight.current.delete(orderNo) } }, [])
  useEffect(() => { if (!loading && active && !tracking[active]) void getTracking(active) }, [active, getTracking, loading, tracking])
  return <div className="min-h-screen bg-muted/25"><header className="border-b bg-background"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Package className="size-5" /></div><div><p className="text-sm font-semibold">Order desk</p><p className="text-[11px] text-muted-foreground">Australian orders & shipping</p></div></div><Badge variant="outline" className="gap-1.5"><FlaskConical className="size-3" />Assessment</Badge></div></header><main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-8 sm:py-10"><div><p className="mb-2 text-xs font-medium uppercase tracking-widest text-muted-foreground">Orders / Details</p><h1 className="text-3xl font-semibold tracking-tight">Order details</h1><p className="mt-2 text-sm text-muted-foreground">Products, GST breakdown and shipment tracking in one place.</p></div>{loading ? <div role="status" className="space-y-5"><Skeleton className="h-10 w-80 max-w-full" /><Skeleton className="h-32 w-full" /><Skeleton className="h-80 w-full" /></div> : error ? <Alert variant="destructive"><TriangleAlert /><AlertTitle>Orders are unavailable</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : orders.length === 0 ? <Card><CardContent className="py-16 text-center">No orders yet</CardContent></Card> : <Tabs value={active} onValueChange={setActive} className="gap-6"><TabsList className="h-auto max-w-full flex-wrap justify-start p-1" aria-label="Select an order">{orders.map((order, i) => <TabsTrigger key={order.order_no} value={order.order_no}>Order {i + 1}<span className="ml-1 hidden sm:inline">· {order.company}</span></TabsTrigger>)}</TabsList>{orders.map(order => <TabsContent key={order.order_no} value={order.order_no}><Details order={order} state={tracking[order.order_no]} refresh={() => void getTracking(order.order_no)} /></TabsContent>)}</Tabs>}<footer className="border-t pt-5 text-xs text-muted-foreground">AUD · GST 10% · Product images are open-source Lucide placeholders</footer></main></div>
}
